Entity 초기 세팅
EFUB-SURFERS/BagEasy-back pull request #2
Opened 2023-07-04 03:01 UTC by aqswa

### 요약
Entity 초기 세팅

### 변경 사항
ERD에 따른 도메인과 엔티티 추가

### To Reviewers

2023-07-05 12:46 UTC, ParkIsComing requested changes

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/chat/domain/Chat.java
> +@AllArgsConstructor
```suggestion
@Document(collection = "chat")
@Getter
@AllArgsConstructor 
@Builder
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/chat/domain/Chat.java
> +    @Column(nullable = false)
다른 프로젝트들 참고해보니 @Id 이외에는 별다른 애노테이션을 사용하지 않는 것 같아서 빼도 될 것 같습니다!
```suggestion
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/chat/domain/Chat.java
> +    @Column(nullable = false)
```suggestion
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/chat/domain/Chat.java
> +    @Column(nullable = false)
```suggestion
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/chat/domain/Chat.java
> +    @Column(nullable = false)
```suggestion
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/chat/domain/Chat.java
> +    @Column(nullable = false)
```suggestion
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/chat/domain/Chat.java
> +    @Column(nullable = false)
```suggestion
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/chat/domain/Chat.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
```suggestion
```
MongoDB와 같은 분산 database에서는 key를 서버에서 만들지 않고 클라이언트에서 만든다고 합니다. 그래서 @GeneratedValue는 필요없을 것 같습니다!

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/post/domain/Post.java
> +}
```suggestion
    @Column(name="buyer_id")
    private Long buyerId;
}
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/post/domain/Post.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false, name="school_id")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/post/domain/Post.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false, name="member_id")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/post/domain/Post.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false, name="is_sold")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/comment/Comment.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
```suggestion
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/comment/Comment.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false, name = "is_secret")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/comment/Comment.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false, name = "post_id")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/heart/domain/Heart.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
```suggestion
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/heart/domain/Heart.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false, name = "member_id")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/heart/domain/Heart.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false, name = "post_id")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/image/Image.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
```suggestion
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/image/Image.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false, name = "image_url")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/image/Image.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false, name = "post_id")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/member/domain/Member.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
```suggestion
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/member/domain/Member.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false, name = "school_id")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/post/domain/Post.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
```suggestion
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/reply/domain/Reply.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
```suggestion
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id)
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/reply/domain/Reply.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false, name = "is_secret")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/reply/domain/Reply.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false, name = "comment_id")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/room/domain/Room.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
```suggestion
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/room/domain/Room.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false, name = "member_id")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/room/domain/Room.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false, name = "post_id")
```

2023-07-05 12:46 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/school/domain/School.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
```suggestion
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
```

2023-07-05 12:50 UTC, xyzwv approved these changes

2023-07-05 12:50 UTC, xyzwv commented on src/main/java/com/efub/bageasy/domain/member/domain/Member.java
> +    @Column(nullable = false)
파견교는 나중에 설정할 수 있는 항목이라 초기에 null값이 들어가도 된다고 생각해서 
ERD도 그렇게 작성해두었던 것 같은데, 지금 확인해보니 NOT NULL로 바뀌어있네요.
ERD에서 NULL로 바꾸고, 이 nullable 속성도 true로 두는 게 어떨까요?

2023-07-05 12:54 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/member/domain/Member.java
> +    @Column(nullable = false)
넵 null인게 맞는것같습니다.

2023-07-05 13:35 UTC, nammsamm commented on src/main/java/com/efub/bageasy/domain/comment/Comment.java
> +    private Long postId;
혹시 memberId가 없는 것이 맞을까요?

2023-07-05 13:35 UTC, nammsamm commented on src/main/java/com/efub/bageasy/domain/reply/domain/Reply.java
> +    private Long commentId;
ERD에는 memberId가 포함되어 있는데용, 혹시 memberId가 없는 것이 맞을까요?

2023-07-06 07:08 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/comment/Comment.java
> +    private Long postId;
@aqswa 댓글, 대댓글 다 memberId 추가하는 게 맞을 것 같은데 일부러 빼신건가요??

2023-07-06 08:45 UTC, nammsamm approved these changes

2023-07-06 09:33 UTC, ParkIsComing approved these changes

2023-07-06 09:33 UTC, merged