feat : 대댓글 생성, 삭제, 조회
EFUB-SURFERS/BagEasy-back pull request #9
Opened 2023-07-15 14:15 UTC by nammsamm

### 요약
- 대댓글 생성 구현
- 대댓글 조회 구현
- 대댓글 삭제 구현

### 변경 사항
- 엔티티에 연관관계 만들었습니다.

### To Reviewers

2023-07-15 22:58 UTC, ParkIsComing approved these changes

2023-07-15 22:58 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/reply/service/ReplyService.java
`@Transactional` 추가해주세요

2023-07-16 12:12 UTC, xyzwv requested changes

2023-07-16 12:12 UTC, xyzwv commented on src/main/java/com/efub/bageasy/domain/reply/service/ReplyService.java
> +    public Reply findReply(Long replyId){
읽기만 하는 메소드에는 @Transactional(readonly=true) 붙여주시면 더 좋을 것 같습니다

2023-07-16 12:12 UTC, xyzwv commented on src/main/java/com/efub/bageasy/domain/reply/service/ReplyService.java
> +    public void deleteReply(Member member, Long replyId) {
대댓 작성자랑 로그인한 회원이 같아야 삭제된다는 조건이 필요해 보입니다

2023-07-17 08:04 UTC, xyzwv approved these changes

2023-07-17 10:06 UTC, ParkIsComing approved these changes

2023-07-17 10:06 UTC, ParkIsComing commented on src/main/java/com/efub/bageasy/domain/reply/repository/ReplyRepository.java
> +    List<Reply> findAllByCommentId(Long commentId);
작성순으로 정렬해서 받아오도록 수정해주세요. db는 작성 순서대로 읽는것을 보장하지 않습니다.

2023-07-17 23:48 UTC, merged